### ISSUE TITLE
cluster tree and dendrogram

### ISSUE THREAD

**Issue by antoine4ucsd** [markrobinsonuzh/cytofWorkflow#24] opened 2020-12-10 16:45 UTC
Hello
I am analyzing flow data with your package and it works really well. thank you
I am now trying to refine the output. I am particularly interested in generating cluster tree from the cluster output I got with the cluster function.
Is there a way to generate smthg like the one attached or even better to make use of this nice package? 
https://nbisweden.github.io/single-cell_sib_scilifelab/session-clustering/clustering.html
 

thank you

![_test](https://user-images.githubusercontent.com/18502631/101802113-f2b64f80-3ac3-11eb-8ecd-04d0776f37bb.png)

**Comment by HelenaLC** [comment] 2020-12-11 15:22
duplicate of https://github.com/HelenaLC/CATALYST/issues/168

**Closed as completed by HelenaLC** 2020-12-11 15:22 UTC
